<?php
/**
 * @version		$Id: testimonies.php $
 * @package		Joomla.Site
 * @subpackage	com_testimonies
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		kiennh
 * This component was generated by http://xipat.com/ - 2015
 */

// no direct access
defined('_JEXEC') or die;

// Include dependancies
jimport('joomla.application.component.controller');

$controller = JControllerLegacy::getInstance('Testimonies');
$controller->execute(JFactory::getApplication()->input->get('task'));
$controller->redirect();

