<?php  
/**
 * @version        $Id: default.php $
 * @package        Joomla.Site
 * @subpackage    com_testimonies
 * @copyright    Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license        GNU General Public License version 2 or later; see LICENSE.txt
 * @author        kiennh
 * This component was generated by http://xipat.com/ - 2015
 */

// no direct access
defined('_JEXEC') or die;
JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');    
?>

<div id="testimonies-list" class="<?php echo 'testimonies-'.$this->layout ?>" class="row">
    <?php foreach($this->items as $item): ?>    
    <div class="items col-xs-12 col-sm-12"> 
        <div class="col-xs-12 col-sm-3 testimonies-left">
            <?php if($this->params->get('show_avatar')) : ?>
            <div class="testimonies-avatar">
                <?php
                    if($item->avatar) echo '<img class="img-responsive" src="'.JURI::base().'images/testimonies/'.$item->avatar.'" alt="" title="" width="76" height="76" />';
                ?>
            </div>
            <?php endif; ?>
            <div class="testimony-name">
                <?php echo $this->escape($item->name); ?> 
            </div> 
            <?php if($this->params->get('show_position') || $this->params->get('show_company') || $this->params->get('show_website')) : ?> 
            <div class="testimonies-info">
                <ul>
                    <?php if($this->escape($item->position)): ?>
                        <li><?php echo $this->escape($item->position); ?></li>
                    <?php endif; ?>
                    <?php if($this->escape($item->company_name)): ?>  
                        <li><?php echo $this->escape($item->company_name); ?></li>
                    <?php endif; ?> 
                    <?php if($this->escape($item->website_url)): ?>  
                        <li><?php echo $this->escape($item->website_url); ?></li>
                    <?php endif; ?> 
                </ul>
            </div>
            <?php endif; ?>
            <?php if($this->params->get('show_rating')) { ?>
            <div class="testimonies-rating"> 
                <?php
                    $ratings = $item->rating;                   
                    for ($i = 1; $i <= $ratings; $i++) {        // go through each star
                        echo '<img src="'.JURI::base().'components/com_testimonies/html/images/star_small_full.png" />';        // show it filled
                    }    
                    $starsLeft = 5 - $ratings;      
                    if ($starsLeft > 0) {                       // if there are any more stars left
                        for ($i = 1; $i <= $starsLeft; $i++) {  // go through each remaining star
                            echo '<img src="'.JURI::base().'components/com_testimonies/html/images/star_small_empty.png" />';     // show it empty
                        }
                    }                      
                ?>
            </div>
            <?php } ?> 
        </div>              
        <div class="testimonies-comment col-xs-12 col-sm-9">
             <span class="testimonies-quote"></span><?php echo $this->escape($item->comment); ?>
        </div>  

    </div> 
    <?php endforeach; ?>
</div>
