<?php
/**
 * @version        $Id: default.php $
 * @package        Joomla.Site
 * @subpackage    com_testimonies
 * @copyright    Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license        GNU General Public License version 2 or later; see LICENSE.txt
 * @author        kiennh
 * This component was generated by http://xipat.com/ - 2015
 */

// no direct access
defined('_JEXEC') or die;
$params = JComponentHelper::getParams('com_testimonies'); 
    if($params->get('captcha') != '' || $params->get('captcha') != 0) {
    JPluginHelper::importPlugin('captcha');
    $dispatcher = JDispatcher::getInstance();
    $dispatcher->trigger('onInit','dynamic_recaptcha_1'); 
}    
?>
<script type="text/javascript">
jQuery(document).ready(function(){
    jQuery(".testimonies-form").show(); 
    jQuery("#testimonies-toggle").click(function(){
      jQuery(".testimonies-form").toggle();
    }); 
});    
</script>
<div id="testimonies-toggle"><a><?php echo JText::_("COM_TESTIMONIES_SHOW_FORM"); ?> <span class="glyphicon glyphicon-triangle-bottom"></span> </a></div>  
<div class="testimonies-form row">
    <div class="col-xs-12 col-sm-5">
        <h3><?php echo JText::_('Submission Form'); ?></h3>
        <div class="form-content">
            <?php echo $params->get('form_content'); ?>
        </div>
    </div>
    <div class="col-xs-12 col-sm-7">
        <form id="testimonies-form" action="<?php echo JRoute::_('index.php'); ?>" method="post" class="form-validate form-horizontal" enctype="multipart/form-data">          
            <div class="control-group form-group">
                <div class="control-label col-sm-4">
                    <?php echo $this->form->getLabel('name'); ?> 
                </div>
                <div class="controls col-sm-8">
                    <?php echo $this->form->getInput('name'); ?>
                </div> 
            </div>
            <div class="control-group form-group">
                <div class="control-label col-sm-4">
                    <?php echo $this->form->getLabel('email'); ?> 
                </div>
                <div class="controls col-sm-8">
                    <?php echo $this->form->getInput('email'); ?>
                </div> 
            </div>                               
            <div class="control-group form-group">
                <div class="control-label col-sm-4">
                    <?php echo $this->form->getLabel('position'); ?> 
                </div>
                <div class="controls col-sm-8">
                    <?php echo $this->form->getInput('position'); ?>
                </div> 
            </div>     
            <div class="control-group form-group">
                <div class="control-label col-sm-4">
                    <?php echo $this->form->getLabel('company_name'); ?> 
                </div>
                <div class="controls col-sm-8">
                    <?php echo $this->form->getInput('company_name'); ?>
                </div> 
            </div>                                               
            <div class="control-group form-group">
                <div class="control-label col-sm-4">
                    <?php echo $this->form->getLabel('rating'); ?> 
                </div>
                <div class="controls col-sm-8">
                    <?php echo $this->form->getInput('rating'); ?>
                </div> 
            </div>                               
            <div class="control-group form-group">
                <div class="control-label col-sm-4">
                    <?php echo $this->form->getLabel('website_url'); ?> 
                </div>
                <div class="controls col-sm-8">
                    <?php echo $this->form->getInput('website_url'); ?>
                </div> 
            </div>   
            <div class="control-group form-group">
                <div class="control-label col-sm-4">
                    <?php echo $this->form->getLabel('avatar'); ?> 
                </div>
                <div class="controls col-sm-8">
                    <?php echo $this->form->getInput('avatar'); ?>
                </div> 
            </div>                                             
            <div class="control-group form-group">
                <div class="control-label col-sm-4">
                    <?php echo $this->form->getLabel('comment'); ?> 
                </div>
                <div class="controls col-sm-8">
                    <?php echo $this->form->getInput('comment'); ?>
                </div> 
            </div>  
			<?php if($params->get('captcha') != '' || $params->get('captcha') != 0): ?>
            <div class="control-group form-group">
                <div class="control-label col-sm-4">
                    <?php echo $this->form->getLabel('captcha'); ?> 
                </div>
                <div class="controls col-sm-8">
                    <div id="dynamic_recaptcha_1"></div>
                </div> 
            </div>
			<?php endif; ?>
            <div class="control-group form-group">
                <div class="control-label col-sm-4">
                </div>
                <div class="controls col-sm-8">
                    <button class="btn btn-primary" type="submit"><?php echo JText::_('Send Testimonnial'); ?></button>                    
                </div> 
            </div>                           
                <input type="hidden" name="option" value="com_testimonies" />
                <input type="hidden" name="task" value="save" />
                <input type="hidden" name="return" value="<?php echo $this->return_page; ?>" />
                <input type="hidden" name="id" value="" />
                <?php echo JHtml::_('form.token'); ?>
        </form>    
    </div>
</div>

