<?php
/**
 * @version		$Id: default.php $
 * @package		Joomla.Site
 * @subpackage	com_testimonies
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		kiennh
 * This component was generated by http://xipat.com/ - 2015
 */

// no direct access
defined('_JEXEC') or die;
JHtml::addIncludePath(JPATH_COMPONENT . '/helpers'); 
?>
<div class="row">
    <?php if($this->freetext): ?>
    <div class="testimonies-freetext"><?php echo $this->freetext; ?></div>
    <?php endif; ?>
<?php
        switch ($this->layout) {
            case 'quote_list':
                echo $this->loadTemplate('quote_list');
                break;
            case 'grid':
                echo $this->loadTemplate('grid');
                break; 
            case 'quote_grid':
                echo $this->loadTemplate('quote_grid');
                break;
            case 'cardbox':
                echo $this->loadTemplate('cardbox'); 
                break; 
            case 'cardbox2':
                echo $this->loadTemplate('cardbox2'); 
                break;                                                                   
            default:  
                break;
        }
?>     
<?php if($this->layout == 'default') { ?>
<div id="testimonies-list" class="<?php echo 'testimonies-'.$this->layout ?>" class="row">
	<?php foreach($this->items as $item): ?>	
    <div class="items col-xs-12 col-sm-12"> 
        <?php if($this->params->get('show_avatar')) : ?>
        <div class="testimonies-avatar">
            <?php
                if($item->avatar) echo '<img src="'.JURI::base().'images/testimonies/'.$item->avatar.'" alt="" title="" width="85" height="85" />';
            ?>
        </div>
        <?php endif; ?>
        <div class="testimonies-comment">
             <?php echo $this->escape($item->comment); ?>
        </div>
		<div class="testimony-name">
            <?php echo $this->escape($item->name); ?> 
        </div>
        <?php if($this->params->get('show_position') || $this->params->get('show_company') || $this->params->get('show_website')) : ?> 
        <div class="testimonies-info">
            <ul>
                <?php if($this->escape($item->position)): ?>
                    <li><?php echo $this->escape($item->position); ?></li>
                <?php endif; ?>
                <?php if($this->escape($item->company_name)): ?>  
                    <li><?php echo $this->escape($item->company_name); ?></li>
                <?php endif; ?> 
                <?php if($this->escape($item->website_url)): ?>  
                    <li><?php echo $this->escape($item->website_url); ?></li>
                <?php endif; ?> 
            </ul>
        </div>
        <?php endif; ?>
        <?php if($this->params->get('show_rating')) { ?>
        <div class="testimonies-rating"> 
            <?php
                $ratings = $item->rating;                   
                for ($i = 1; $i <= $ratings; $i++) {        // go through each star
                    echo '<img src="'.JURI::base().'components/com_testimonies/html/images/star_full.png" />';        // show it filled
                }    
                $starsLeft = 5 - $ratings;      
                if ($starsLeft > 0) {                       // if there are any more stars left
                    for ($i = 1; $i <= $starsLeft; $i++) {  // go through each remaining star
                        echo '<img src="'.JURI::base().'components/com_testimonies/html/images/star_empty.png" />';     // show it empty
                    }
                }                      
            ?>
        </div>
        <?php } ?>

    </div>       
	<?php endforeach; ?>
</div>     
<?php } ?> 
<div class="clearfix"> </div>
<div align="center">
    <div class="pagination">  
	    <?php echo $this->pagination->getPagesLinks(); ?>
    </div>
</div>
</div>
<?php echo $this->loadTemplate('form'); ?>  
  
