<?php  
/**
 * @version        $Id: default.php $
 * @package        Joomla.Site
 * @subpackage    com_testimonies
 * @copyright    Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license        GNU General Public License version 2 or later; see LICENSE.txt
 * @author        kiennh
 * This component was generated by http://xipat.com/ - 2015
 */

// no direct access
defined('_JEXEC') or die;  
?>
<div class="row">
    <div class="testimonies-thankyou">
        <img src="<?php echo JURI::base(); ?>components/com_testimonies/html/images/tick.png" alt="" title="" width="128">
        <div class="testimonies-thankyou-title"><?php echo JText::_('TESTIMONIAL_THANKYOU_TITLE'); ?></div>
        <div class="testimonies-thankyou-content"><?php echo JText::_('TESTIMONIAL_THANKYOU_CONTENT'); ?></div>
    </div>
</div>


