CREATE TABLE IF NOT EXISTS `#__testimonies` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255)  NOT NULL ,
  `email` VARCHAR(255)  NOT NULL ,
  `avatar` TEXT NOT NULL ,
  `website_url` TEXT NOT NULL ,
  `position` varchar(255) NOT NULL ,
  `company_name` varchar(255) NOT NULL ,
  `comment` TEXT NOT NULL ,
  `rating` int(11) NOT NULL DEFAULT '0',
  `state` TINYINT(3) NOT NULL DEFAULT '0',
  `featured` TINYINT(3) NOT NULL DEFAULT '0',
  `ordering` INTEGER NOT NULL DEFAULT '0',
  `metakey` TEXT NOT NULL,
  `metadesc` text NOT NULL,
  `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` int(10) unsigned NOT NULL DEFAULT '0',
  `modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` int(10) unsigned NOT NULL DEFAULT '0',
  `checked_out` int(10) unsigned NOT NULL DEFAULT '0',
  `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `publish_up` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `publish_down` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `language` char(7) NOT NULL DEFAULT '',
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='';
