<?php
/**
 * @version		$Id: edit.php $
 * @package		Joomla.Administrator
 * @subpackage	com_testimonies
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		kiennh
 * This component was generated by http://xipat.com/ - 2015
 */

// no direct access
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT.'/helpers/html');
JHtml::_('behavior.tooltip');
JHtml::_('behavior.formvalidation');        
?>
<script type="text/javascript">
	Joomla.submitbutton = function(task)
	{
		if (task == 'item.cancel' || document.formvalidator.isValid(document.id('item-form'))) {
			Joomla.submitform(task, document.getElementById('item-form'));
		}
	}
</script>

<form action="<?php echo JRoute::_('index.php?option=com_testimonies&layout=edit&id='.(int) $this->item->id); ?>" method="post" name="adminForm" id="item-form" class="form-validate" enctype="multipart/form-data">
	<div class="form-horizontal">
        <?php echo JHtml::_('bootstrap.startTabSet', 'myTab', array('active' => 'details')); ?>
        <?php echo JHtml::_('bootstrap.addTab', 'myTab', 'details', empty($this->item->id) ? JText::_('COM_TESTIMONIES_NEW_ITEM') : JText::sprintf('COM_TESTIMONIES_ITEM_DETAILS', $this->item->id)); ?>                
        <div class="row-fluid"> 
            <div class="control-group">
                <div class="control-label">
                    <?php echo $this->form->getLabel('id'); ?> 
                </div>
                <div class="controls">
                    <?php echo $this->form->getInput('id'); ?>
                </div> 
            </div>            
            <div class="control-group">
                <div class="control-label">
                    <?php echo $this->form->getLabel('name'); ?> 
                </div>
                <div class="controls">
                    <?php echo $this->form->getInput('name'); ?>
                </div> 
            </div>
            <div class="control-group">
                <div class="control-label">
                    <?php echo $this->form->getLabel('email'); ?> 
                </div>
                <div class="controls">
                    <?php echo $this->form->getInput('email'); ?>
                </div> 
            </div>    
            <div class="control-group">
                <div class="control-label">
                    <?php echo $this->form->getLabel('position'); ?> 
                </div>
                <div class="controls">
                    <?php echo $this->form->getInput('position'); ?>
                </div> 
            </div>     
            <div class="control-group">
                <div class="control-label">
                    <?php echo $this->form->getLabel('company_name'); ?> 
                </div>
                <div class="controls">
                    <?php echo $this->form->getInput('company_name'); ?>
                </div> 
            </div>                               				
            <div class="control-group">
                <div class="control-label">
                    <?php echo $this->form->getLabel('rating'); ?> 
                </div>
                <div class="controls">
                    <?php echo $this->form->getInput('rating'); ?>
                </div> 
            </div>            			
            <div class="control-group">
                <div class="control-label">
                    <?php echo $this->form->getLabel('website_url'); ?> 
                </div>
                <div class="controls">
                    <?php echo $this->form->getInput('website_url'); ?>
                </div> 
            </div>
            <div class="control-group">
                <div class="control-label">
                    <?php echo $this->form->getLabel('avatar'); ?> 
                </div>
                <div class="controls">
                    <?php echo $this->form->getInput('avatar'); ?>
                    <?php if($this->item->avatar): ?>
                        <img alt="Avatar" src="<?php echo JUri::root().'images/testimonies/'.$this->item->avatar ?>" width="80" height="80" />
                    <?php endif; ?>
                </div> 
            </div>                	
            <div class="control-group">
                <div class="control-label">
                    <?php echo $this->form->getLabel('comment'); ?> 
                </div>
                <div class="controls">
                    <?php echo $this->form->getInput('comment'); ?>
                </div> 
            </div>            
            <div class="control-group">
                <div class="control-label">
                    <?php echo $this->form->getLabel('state'); ?> 
                </div>
                <div class="controls">
                    <?php echo $this->form->getInput('state'); ?>
                </div> 
            </div> 
            <div class="control-group">
                <div class="control-label">
                    <?php echo $this->form->getLabel('featured'); ?> 
                </div>
                <div class="controls">
                    <?php echo $this->form->getInput('featured'); ?>
                </div> 
            </div>                            			
            <div class="control-group">
                <div class="control-label">
                    <?php echo $this->form->getLabel('created'); ?> 
                </div>
                <div class="controls">
                    <?php echo $this->form->getInput('created'); ?>
                </div> 
            </div>                				
        </div>			
        <?php echo JHtml::_('bootstrap.endTab'); ?> 

    <?php echo JHtml::_('bootstrap.endTabSet'); ?> 
</div>
    <input type="hidden" name="task" value="" />
    <?php echo JHtml::_('form.token'); ?>
<div class="clr"></div>
</form>
