<?php
/**
 * version $Id: view.html.php $
 * @package		Joomla.Site
 * @subpackage	com_content
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		kiennh
 * This component was generated by http://xipat.com/ - 2015
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die;

jimport('joomla.application.component.view');      

/**
 * HTML View class for the Content component
 *
 * @package		Joomla.Site
 * @subpackage	com_content
 * @since 1.5
 */
class TestimoniesViewList extends JViewLegacy
{
	protected $items;
	protected $pagination;
    protected $state;
    protected $return_page;

	function display($tpl = null)
	{
        $app = JFactory::getApplication(); 
        $params = $app->getParams();          
        $this->form        = $this->get('Form');  
		$this->items		= $this->get('Items');
		$this->pagination 	= $this->get('Pagination');  
        $this->freetext = $params->get('freetext');      
        $this->layout =  $params->get('testimonies_layout');
        $this->params = $params;   
		// Check for errors.
		if (count($errors = $this->get('Errors'))) {
			JError::raiseError(500, implode("\n", $errors));
			return false;
		} 

		$this->_prepareDocument();
        $document = JFactory::getDocument(); 
        if($params->get('use_bootstrap')) {
            $document->addStyleSheet(JURI::root(true).'/components/com_testimonies/html/css/bootstrap.min.css');
            $document->addStyleSheet(JURI::root(true).'/components/com_testimonies/html/css/bootstrap-theme.min.css');
            $document->addScript(JURI::root(true).'/components/com_testimonies/html/js/jquery.min.js');
            $document->addScript(JURI::root(true).'/components/com_testimonies/html/js/bootstrap.min.js');
        }
        
        $document->addStyleSheet(JURI::root(true).'/components/com_testimonies/html/css/style.css');
        
        if (JRequest::getVar('layout'))
        {
            $this->setLayout('thankyou');    
        }  
                
		parent::display($tpl);
	}

	/**
	 * Prepares the document
	 */
	protected function _prepareDocument()
	{
		//TODO: prepare document
	}
}
