<?php
/**
 * @version		$Id: items.php $
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		kiennh
 * This component was generated by http://xipat.com/ - 2015
 */
 
/**
 Generate by Component Gen Code - 2012
 */

defined('_JEXEC') or die;

jimport('joomla.application.component.modellist');

/**
 * Methods supporting a list of Items records.
 *
 * @package		Joomla.Administrator
 * @subpackage	com_testimonies
 * @since		1.6
 */
class TestimoniesModelItems extends JModelList
{
	/**
	 * Constructor.
	 *
	 * @param	array	An optional associative array of configuration settings.
	 * @see		JController
	 * @since	1.6
	 */
	public function __construct($config = array())
	{
		if (empty($config['filter_fields'])) {
			$config['filter_fields'] = array(
				'id', '#__testimonies.id',
                'state', '#__testimonies.state',
				'featured', '#__testimonies.featured',
				'name', '#__testimonies.name', 'email', '#__testimonies.email', 'website_url', '#__testimonies.website_url', 'comment', '#__testimonies.comment', 'state', '#__testimonies.state', 'ordering', '#__testimonies.ordering'
			);
		}

		parent::__construct($config);
	}
	
	
	
	#FUNCTION_GET_AUTHOR#

	/**
	 * Build an SQL query to load the list data.
	 *
	 * @return	JDatabaseQuery
	 * @since	1.6
	 */
	protected function getListQuery()
	{
		// Initialise variables.
		$db		= $this->getDbo();
		$query	= $db->getQuery(true);

		// Select the required fields from the table.
		$query->select(
			$this->getState(
				'list.select',
				'#__testimonies.id, #__testimonies.state, #__testimonies.featured, #__testimonies.checked_out AS checked_out, #__testimonies.checked_out_time AS checked_out_time, 
				#__testimonies.publish_up, #__testimonies.publish_down, #__testimonies.ordering, #__testimonies.created  
				, #__testimonies.name, #__testimonies.email, #__testimonies.website_url, #__testimonies.comment, #__testimonies.state, #__testimonies.ordering'
			)
		);
		$query->from('`#__testimonies`');

		// Join over the users for the checked out user.
		$query->select('uc.name AS editor');
		$query->join('LEFT', '#__users AS uc ON uc.id=#__testimonies.checked_out');
		
		
		
		// Filter by published state
							$published = $this->getState('filter.state');
							if (is_numeric($published)) {
								$query->where('#__testimonies.state = '.(int) $published);
							} else if ($published === '') {
								$query->where('(#__testimonies.state IN (0, 1))');
							}
						
		
		// Filter by search
						$search = $this->getState('filter.search');
						if (!empty($search))
						{							
							$searchLike = $db->Quote('%'.$db->escape($search, true).'%');
							$search = $db->Quote($db->escape($search, true));
						$query->where('(#__testimonies.name = '.$search.' OR #__testimonies.email = '.$search.' OR #__testimonies.comment = '.$search.')');
							} //end search
		
		// Add the list ordering clause.
		$orderCol	= $this->state->get('list.ordering');
		$orderDirn	= $this->state->get('list.direction');
		
		$query->order($db->escape($orderCol.' '.$orderDirn));

		//echo nl2br(str_replace('#__','jos_',$query));
		return $query;
	}

	/**
	 * Returns a reference to the a Table object, always creating it.
	 *
	 * @param	type	The table type to instantiate
	 * @param	string	A prefix for the table class name. Optional.
	 * @param	array	Configuration array for model. Optional.
	 * @return	JTable	A database object
	 * @since	1.6
	 */
	public function getTable($type = 'Items', $prefix = 'TestimoniesTable', $config = array())
	{
		return JTable::getInstance($type, $prefix, $config);
	}

	/**
	 * Method to auto-populate the model state.
	 *
	 * Note. Calling getState in this method will result in recursion.
	 *
	 * @since	1.6
	 */
	protected function populateState($ordering = null, $direction = null)
	{
		// Initialise variables.
		$app = JFactory::getApplication('administrator');

		// Load the filter state.
		$search = $this->getUserStateFromRequest($this->context.'.filter.search', 'filter_search');
							$this->setState('filter.search', $search);
		
		$state = $this->getUserStateFromRequest($this->context.'.filter.state', 'filter_state', '', 'string');
							$this->setState('filter.state', $state);
		
		
		
		
		
		

		// List state information.
		parent::populateState('#__testimonies.id', 'DESC');
	}
}